services:
  backup:
    image: offen/docker-volume-backup:v2
    environment:
      - BACKUP_CRON_EXPRESSION=24 16 * * *
      - BACKUP_COMPRESSION=gz
      - GZIP_PARALLELISM=2
      - BACKUP_FILENAME=backup-%Y-%m-%dT%H-%M-%S.{{"{{"}} .Extension {{"}}"}}
      - BACKUP_FILENAME_EXPAND=true
      - BACKUP_LATEST_SYMLINK=backup.latest.tar.gz
      - BACKUP_FROM_SNAPSHOT=false
      - BACKUP_RETENTION_DAYS=7
      - BACKUP_PRUNING_LEEWAY=1m
      - BACKUP_PRUNING_PREFIX=backup-
      - BACKUP_STOP_SERVICE_TIMEOUT=5m
      - NOTIFICATION_LEVEL=info
      - EXEC_FORWARD_OUTPUT=true
      - BACKUP_SOURCES=/var/lib/docker/volumes
    volumes:
      # Monte todos os volumes locais para backup
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      # Diretório local para armazenar backups
      - /var/backups:/backup
      # Socket Docker para gerenciar containers durante o backup
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M
      placement:
        constraints:
          - node.labels.backup-node == true
