  backup:
    image: offen/docker-volume-backup:v2
    environment:
      # Frequência do backup (cron)
      BACKUP_CRON: "0 2 * * *" # Faz backup todo dia às 02:00
      # Nome do backup
      BACKUP_NAME: flow-backup
      # Número de backups antigos para manter
      BACKUP_KEEP: 3
    volumes:
      # Monte todos os volumes locais para backup
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      # Diretório local para armazenar backups
      - /path/to/local_backups:/archive
      # Socket Docker para gerenciar containers durante o backup
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deployment:
      replicas: 1
      restart_policy:
        condition: always
      resources:
        limits:
          memory: 50M
      placement:
        constraints:
          - node.labels.backup-node == true
