services:
  backup:
    image: offen/docker-volume-backup:v2
    environment:
      - BACKUP_CRON_EXPRESSION="0 10 * * *"
      - BACKUP_COMPRESSION="gz"
      - GZIP_PARALLELISM=2
      - BACKUP_FILENAME="backup-%Y-%m-%dT%H-%M-%S.{{ .Extension }}"
      - BACKUP_FILENAME_EXPAND="true"
      - BACKUP_LATEST_SYMLINK="backup.latest.tar.gz"
      - BACKUP_FROM_SNAPSHOT="false"
      - BACKUP_RETENTION_DAYS="7"
      - BACKUP_PRUNING_LEEWAY="1m"
      - BACKUP_PRUNING_PREFIX="backup-"
      - BACKUP_STOP_SERVICE_TIMEOUT="5m"
      - NOTIFICATION_URLS=smtp://contato@jadersantos.com.br:J@der1472@host:587/?fromAddress=contato@jadersantos.com.br&toAddresses=msantos.jader@gmail.com
      - NOTIFICATION_LEVEL="info"
      - EXEC_FORWARD_OUTPUT=true
      - EXEC_LABEL="database"
    volumes:
      # Monte todos os volumes locais para backup
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      # Diretório local para armazenar backups
      - /var/backups:/archive
      # Socket Docker para gerenciar containers durante o backup
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deployment:
      replicas: 1
      restart_policy:
        condition: always
      resources:
        limits:
          memory: 50M
      placement:
        constraints:
          - node.labels.backup-node == true
