  backup:
    image: offen/docker-volume-backup:v2
    volumes:
      - /var/lib/docker/volumes
    deployment:
      replicas: 1
      resources:
        limits:
          memory: 50M
      placement:
        constraints:
          - node.labels.backup-node == true
