services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    restart: always
    volumes:
         - appsmith_data:/appsmith-stacks
    networks:
      - proxy_network
    environment:
      - APPSMITH_SIGNUP_DISABLED=FALSE
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback 
        monitor: 60s
        max_failure_ratio: 0.2
      placement:
        constraints:
          - node.role == manager
volumes:
  appsmith_data:
    external: true
networks:
  proxy_network:
    external: true
